cleaning up, nuking atom, updating install scripts

diff --git a/script/install b/script/install
--- a/script/install
+++ b/script/install
@@ -1,14 +1,37 @@
 #!/usr/bin/env bash
 
+# Run all dotfiles installers.
+
+set -e
+
+cd "$(dirname $0)"/..
+
+# Run Homebrew through the Brewfile
+echo "› brew bundle"
+brew bundle
+
+# find the installers and run them iteratively
+find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
+
+
+
+
+
+
+
+
+
+
+
 #
 # Install dotfiles from the git repo, and bootstrap your system
 #
 
-if [[ ! -d ~/.dotfiles ]]; then
-	echo "Installing tomichj/dotfiles"
-	git clone https://github.com/tomichj/dotfiles ~/.dotfiles
-	~/.dotfiles/script/bootstrap
-	~/.dotfiles/bin/dot
-else
-	echo "Aborting; you have an existing .dotfiles directory."
-fi
+# if [[ ! -d ~/.dotfiles ]]; then
+# 	echo "Installing tomichj/dotfiles"
+# 	git clone https://github.com/tomichj/dotfiles ~/.dotfiles
+# 	~/.dotfiles/script/bootstrap
+# 	~/.dotfiles/bin/dot
+# else
+# 	echo "Aborting; you have an existing .dotfiles directory."
+# fi
